📦 NEW: IR for Blaupunkt and Grundig TV
logickworkshop/Flipper-IRDB pull request #481
Opened 2023-05-08 18:23 UTC by nnesetto

2023-05-08 18:31 UTC, darmiel requested changes
Looks good so far, you already fixed the naming issues, but please remove the .gitignore file :)

2023-05-08 18:31 UTC, darmiel commented on TVs/Blaupunkt/Blaupunkt.ir
> +name: Vol_up
```suggestion
name: VOL+
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Blaupunkt/Blaupunkt.ir
> +name: Vol_down
```suggestion
name: VOL-
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Blaupunkt/Blaupunkt.ir
> +name: Ch_down
```suggestion
name: CH-
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Blaupunkt/Blaupunkt.ir
> +name: Power
```suggestion
name: POWER
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +name: Power
```suggestion
name: POWER
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +name: Vol_up
```suggestion
name: VOL+
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +name: Vol_down
```suggestion
name: VOL-
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +name: Ch_up
```suggestion
name: CH+
```

2023-05-08 18:31 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +name: Ch_down
```suggestion
name: CH-
```

2023-05-08 18:31 UTC, darmiel commented on .gitignore
Please remove this file from the PR

2023-05-08 18:34 UTC, darmiel commented on TVs/Blaupunkt/Blaupunkt.ir
> +#
Can you add a comment with the TV model here?

```suggestion
# 
# Blaupunkt XYZ
#
```

2023-05-08 18:34 UTC, darmiel commented on TVs/Grundig/Grundig_2.ir
> +#
```suggestion
# 
# Here aswell :)
#
```

2023-05-09 06:58 UTC, nnesetto commented
I restored the state of .gitignore to what it was in the original repository.

Regarding TV models, unfortunately, I do not know what models they were because they were in the hotel.

2023-05-09 07:44 UTC, darmiel commented
> I restored the state of .gitignore to what it was in the original repository.
> 
> Regarding TV models, unfortunately, I do not know what models they were because they were in the hotel.

Alright, that's fine. Thank you very much 🙂

2023-05-09 07:52 UTC, merged